<div class="pro">
    <div class="tone"> {dede:arclist titlelen='220' row='1' flag='h'} <a href="[field:arcurl /]" title="[field:title/]">[field:image/]</a> {/dede:arclist} </div>
    <ul class="clearfix">
      {dede:arclist titlelen='220' row='3' noflag='h'}
      <li><a href="[field:arcurl /]" title="[field:title/]">[field:image /]</a></li>
      {/dede:arclist}
    </ul>
    <h3><a href="{dede:field name='typeurl'/}">更多{dede:field name='typename'/}<span>&gt;&gt;</span></a></h3>
  </div>