<?php
$z[0]=Array("arclist"," <a href=\"[field:arcurl /]\" title=\"[field:title/]\">[field:image/]</a> ",42,173);
$z[0][4]['titlelen']="220";
$z[0][4]['row']="1";
$z[0][4]['flag']="h";
$z[1]=Array("arclist","\r\n      <li><a href=\"[field:arcurl /]\" title=\"[field:title/]\">[field:image /]</a></li>\r\n      ",215,372);
$z[1][4]['titlelen']="220";
$z[1][4]['row']="3";
$z[1][4]['noflag']="h";
$z[2]=Array("field","",402,430);
$z[2][4]['name']="typeurl";
$z[3]=Array("field","",438,467);
$z[3][4]['name']="typename";

?>