<?php
$z[0]=Array("field","",36,64);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",73,102);
$z[1][4]['name']="typename";
$z[2]=Array("field","",104,133);
$z[2][4]['name']="typename";
$z[3]=Array("arclist","\r\n        <div class=\"img\"><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:image/]</a></div>\r\n        ",177,384);
$z[3][4]['titlelen']="";
$z[3][4]['row']="1";
$z[3][4]['flag']="c";
$z[3][4]['imgwidth']="120";
$z[3][4]['imgheight']="120";
$z[4]=Array("arclist","\r\n        <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></li>\r\n        ",440,599);
$z[4][4]['titlelen']="220";
$z[4][4]['row']="4";
$z[4][4]['noflag']="c";
$z[5]=Array("field","",629,657);
$z[5][4]['name']="typeurl";

?>