<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='img'><img src='{@me['litpic']}' alt='{@me['title']}'/></a>\"); ",4,175);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",202,217);
$z[2]=Array("title","",226,240);
$z[3]=Array("title","",242,256);
$z[4]=Array("description","",297,317);
$z[5]=Array("arcurl","",335,350);
$z[6]=Array("title","",359,373);
$z[7]=Array("pubdate","",431,473);
$z[7][4]['function']="GetDateMK(@me)";

?>