<?php
$z[0]=Array("channelartlist","\r\n        <li><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\r\n          <ul>\r\n            {dede:channel type='son' noself='yes'}\r\n            <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n            {/dede:channel}\r\n          </ul>\r\n        </li>\r\n        ",63,424);
$z[0][4]['typeid']="top";
$z[0][4]['row']="5";
$z[1]=Array("global","",492,522);
$z[1][4]['name']="cfg_leftcontact";
$z[2]=Array("global","",582,607);
$z[2][4]['name']="cfg_footer";

?>