<?php
$z[0]=Array("global","",81,108);
$z[0][4]['name']="cfg_seotitle";
$z[1]=Array("global","",110,136);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",203,228);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",275,300);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("global","",341,366);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("global","",395,421);
$z[5][4]['name']="cfg_dataurl";
$z[6]=Array("global","",532,557);
$z[6][4]['name']="cfg_cmsurl";
$z[7]=Array("global","",1002,1027);
$z[7][4]['name']="cfg_cmsurl";
$z[8]=Array("global","",1076,1101);
$z[8][4]['name']="cfg_cmsurl";
$z[9]=Array("global","",1153,1178);
$z[9][4]['name']="cfg_cmsurl";
$z[10]=Array("global","",1227,1252);
$z[10][4]['name']="cfg_cmsurl";
$z[11]=Array("channel","\r\n      <li><a href='[field:typeurl/]' [field:rel/]>[field:typename/]</a></li>\r\n      ",1397,1628);
$z[11][4]['type']="top";
$z[11][4]['row']="10";
$z[11][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~>~typename~</a></li>";

?>